FROM akkerman/rpi-nginx
WORKDIR /tmp
RUN apt-get update
RUN apt-get install wget -y
WORKDIR /opt/kibana
RUN wget https://download.elasticsearch.org/kibana/kibana/kibana-3.1.0.tar.gz --no-check-certificate
RUN mkdir -p /usr/share/nginx/html && tar zxf kibana-3.1.0.tar.gz && cp -r kibana-3.1.0/* /usr/share/nginx/html
ADD config.js /usr/share/nginx/html/config.js
ADD dashboard/logstash-dash.json /usr/share/nginx/html/app/dashboards/default.json
ADD nginx.conf /etc/nginx/nginx.conf

