FROM akkerman/rpi-nginx
WORKDIR /tmp
RUN apt-get update && \
    apt-get install wget -y
WORKDIR /tmp
RUN wget https://grafanarel.s3.amazonaws.com/builds/grafana-2.6.0.linux-x64.tar.gz --no-check-certificate
RUN tar zxf /tmp/grafana-2.6.0.linux-x64.tar.gz && mv grafana-2.6.0/* /usr/share/nginx/www/
ADD config.js /usr/share/nginx/html/config.js
#add default dashboard
ADD dashboards/requests.json /usr/share/nginx/html/app/dashboards/default.json

