FROM sbiermann/rpi-influxdb
MAINTAINER Martin Dilger <martin@effectivetrainings.de>
#based on https://github.com/sbiermann/rpi-influxdb

ADD config.toml /config/config.toml
ADD types.db /config/collectd_types.db
#add run.sh with the fix https://github.com/tutumcloud/influxdb/pull/40/files
ADD run.sh /run.sh
RUN chmod +x /*.sh
CMD ["/run.sh"]

#collectd port
EXPOSE 25826

